services:
  - type: web
    name: cinephile
    env: node
    buildCommand: npm install --include=dev && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PGUSER
        sync: false
      - key: PGPASSWORD
        sync: false
      - key: PGHOST
        sync: false
      - key: PGPORT
        value: "5432"
      - key: PGDATABASE
        sync: false
      - key: TMDB_API_KEY
        sync: false
